spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review_system?useSSL=false
    username:
    password:
    drive-class-name: mysql.cj.jdbc.Driver
  application:
    name: review-system
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
  # SET ACTIVE PROFILE TO THE DEV ENV
  profiles:
    active: dev